/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        display: ['Space Grotesk', 'Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      colors: {
        apex: {
          base:    '#050810',
          surface: '#0a0f1e',
          card:    '#0d1426',
          border:  '#1a2035',
          muted:   '#2a3a5c',
          cyan:    '#22d3ee',
          blue:    '#3b82f6',
          green:   '#34d399',
          amber:   '#fbbf24',
          red:     '#f87171',
          purple:  '#a78bfa',
          'text-primary':   '#f1f5f9',
          'text-secondary': '#94a3b8',
          'text-muted':     '#475569',
        },
      },
      boxShadow: {
        'glow-cyan':   '0 0 30px rgba(34,211,238,0.2), 0 0 60px rgba(34,211,238,0.08)',
        'glow-green':  '0 0 30px rgba(52,211,153,0.2), 0 0 60px rgba(52,211,153,0.08)',
        'glow-red':    '0 0 30px rgba(248,113,113,0.2)',
        'glow-amber':  '0 0 30px rgba(251,191,36,0.2)',
        'glow-purple': '0 0 30px rgba(167,139,250,0.2)',
        'card':        '0 4px 24px rgba(0,0,0,0.5), inset 0 1px 0 rgba(255,255,255,0.04)',
      },
      animation: {
        'pulse-slow':    'pulse 3s cubic-bezier(0.4,0,0.6,1) infinite',
        'fade-in':       'fadeIn 0.4s ease-out',
        'slide-up':      'slideUp 0.5s ease-out',
        'slide-in':      'slideIn 0.4s ease-out',
        'glow-pulse':    'glowPulse 2s ease-in-out infinite',
        'scan-line':     'scanLine 3s linear infinite',
        'float':         'float 6s ease-in-out infinite',
        'orbit':         'orbit 12s linear infinite',
        'data-stream':   'dataStream 2s linear infinite',
        'counter-up':    'counterUp 1s ease-out forwards',
        'progress-fill': 'progressFill 1.5s ease-out forwards',
        'ping-slow':     'ping 2s cubic-bezier(0,0,0.2,1) infinite',
      },
      keyframes: {
        fadeIn:       { from: { opacity: '0' },                          to: { opacity: '1' } },
        slideUp:      { from: { opacity: '0', transform: 'translateY(20px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        slideIn:      { from: { opacity: '0', transform: 'translateX(-16px)' }, to: { opacity: '1', transform: 'translateX(0)' } },
        glowPulse:    { '0%,100%': { opacity: '0.4' }, '50%': { opacity: '1' } },
        scanLine:     { '0%': { transform: 'translateY(-100%)' }, '100%': { transform: 'translateY(100vh)' } },
        float:        { '0%,100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-12px)' } },
        orbit:        { from: { transform: 'rotate(0deg) translateX(80px) rotate(0deg)' }, to: { transform: 'rotate(360deg) translateX(80px) rotate(-360deg)' } },
        dataStream:   { '0%': { backgroundPosition: '0 0' }, '100%': { backgroundPosition: '0 100px' } },
        counterUp:    { from: { opacity: '0', transform: 'translateY(10px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        progressFill: { from: { width: '0%' }, to: { width: 'var(--progress-width)' } },
      },
    },
  },
  plugins: [],
}
